# Generated by Django 3.2.7 on 2021-09-30 02:20

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsuarioModel',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('usuarioId', models.AutoField(db_column='id', primary_key=True, serialize=False, unique=True)),
                ('usuarioNombre', models.CharField(db_column='nombre', max_length=50)),
                ('usuarioApellido', models.CharField(db_column='apellido', max_length=50, verbose_name='Apellido del usuario')),
                ('usuarioCorreo', models.EmailField(db_column='email', max_length=50, unique=True)),
                ('usuarioTipo', models.IntegerField(choices=[(1, 'ADMINISTRADOR'), (2, 'MOZO'), (3, 'CLIENTE')], db_column='tipo')),
                ('password', models.TextField(null=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'usuarios',
            },
        ),
        migrations.CreateModel(
            name='PlatoModel',
            fields=[
                ('platoId', models.AutoField(db_column='id', primary_key=True, serialize=False, unique=True)),
                ('platoNombre', models.CharField(db_column='nombre', max_length=100)),
                ('platoPrecio', models.DecimalField(db_column='precio', decimal_places=2, max_digits=5)),
                ('platoFoto', models.ImageField(db_column='foto', null=True, upload_to='platos/')),
                ('platoCantidad', models.IntegerField(db_column='cantidad', default=0)),
                ('updatedAt', models.DateTimeField(auto_now=True, db_column='updated_at')),
                ('createdAt', models.DateTimeField(auto_now_add=True, db_column='created_at')),
            ],
            options={
                'db_table': 'platos',
            },
        ),
        migrations.CreateModel(
            name='PedidoModel',
            fields=[
                ('pedidoId', models.AutoField(db_column='id', primary_key=True, serialize=False, unique=True)),
                ('pedidoFecha', models.DateTimeField(auto_now_add=True, db_column='fecha')),
                ('pedidoTotal', models.DecimalField(db_column='total', decimal_places=2, max_digits=5)),
                ('cliente', models.ForeignKey(db_column='cliente_id', on_delete=django.db.models.deletion.PROTECT, related_name='clientePedidos', to=settings.AUTH_USER_MODEL)),
                ('vendedor', models.ForeignKey(db_column='vendedor_id', on_delete=django.db.models.deletion.PROTECT, related_name='vendedorPedidos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'pedidos',
            },
        ),
        migrations.CreateModel(
            name='DetallePedidoModel',
            fields=[
                ('detalleId', models.AutoField(db_column='id', primary_key=True, serialize=False, unique=True)),
                ('detalleCantidad', models.IntegerField(db_column='cantidad', validators=[django.core.validators.MinValueValidator(0, 'Valor no puede ser negativo')])),
                ('detalleSubTotal', models.DecimalField(db_column='sub_total', decimal_places=2, max_digits=5)),
                ('pedido', models.ForeignKey(db_column='pedido_id', on_delete=django.db.models.deletion.PROTECT, related_name='pedidoDetalles', to='cms.pedidomodel')),
                ('plato', models.ForeignKey(db_column='plato_id', on_delete=django.db.models.deletion.PROTECT, related_name='platoDetalles', to='cms.platomodel')),
            ],
            options={
                'db_table': 'detalles',
            },
        ),
    ]
