INSERT INTO ALUMNOS (nombre, apellido, correo) VALUES ('Todd', 'Mcfarland', 'sbanks@hotmail.com');
INSERT INTO ALUMNOS (nombre, apellido, correo) VALUES ('Mitchell', 'Taylor', 'rodriguezjeffrey@gmail.com');
INSERT INTO ALUMNOS (nombre, apellido, correo) VALUES ('Kathryn', 'Tate', 'rogersdennis@yahoo.com');
INSERT INTO ALUMNOS (nombre, apellido, correo) VALUES ('Angela', 'Dominguez', 'james95@hill.com');
INSERT INTO ALUMNOS (nombre, apellido, correo) VALUES ('Melissa', 'Lyons', 'flowe@king-watkins.org');
INSERT INTO ALUMNOS (nombre, apellido, correo) VALUES ('Courtney', 'Contreras', 'qcarter@gmail.com');
INSERT INTO ALUMNOS (nombre, apellido, correo) VALUES ('Kathleen', 'Jones', 'hwatson@yu.com');
INSERT INTO ALUMNOS (nombre, apellido, correo) VALUES ('Mark', 'Valdez', 'justinwells@perkins-atkinson.org');
INSERT INTO ALUMNOS (nombre, apellido, correo) VALUES ('Angel', 'Taylor', 'zhill@yahoo.com');
INSERT INTO ALUMNOS (nombre, apellido, correo) VALUES ('John', 'Dennis', 'costajorge@preston.com');
INSERT INTO ALUMNOS (nombre, apellido, correo) VALUES ('Mathew', 'Hall', 'gburton@hotmail.com');
INSERT INTO ALUMNOS (nombre, apellido, correo) VALUES ('Joseph', 'Glover', 'carolinefarrell@yahoo.com');
INSERT INTO ALUMNOS (nombre, apellido, correo) VALUES ('Melanie', 'Thomas', 'christineshepherd@young-morrow.com');
INSERT INTO ALUMNOS (nombre, apellido, correo) VALUES ('Molly', 'Long', 'warnerkathleen@gmail.com');
INSERT INTO ALUMNOS (nombre, apellido, correo) VALUES ('Jessica', 'Norton', 'qwhite@gmail.com');
INSERT INTO ALUMNOS (nombre, apellido, correo) VALUES ('Charles', 'Pham', 'erichensley@atkins.com');
INSERT INTO ALUMNOS (nombre, apellido, correo) VALUES ('Harold', 'Bradley', 'floresalexandria@smith.org');
INSERT INTO ALUMNOS (nombre, apellido, correo) VALUES ('Valerie', 'Watson', 'ljones@hotmail.com');
INSERT INTO ALUMNOS (nombre, apellido, correo) VALUES ('Kenneth', 'Hensley', 'hwilson@hotmail.com');
INSERT INTO ALUMNOS (nombre, apellido, correo) VALUES ('Lisa', 'Knight', 'iowens@hotmail.com');
INSERT INTO ALUMNOS (nombre, apellido, correo) VALUES ('Jeffrey', 'Hall', 'mpalmer@greene-trujillo.net');
INSERT INTO ALUMNOS (nombre, apellido, correo) VALUES ('Mary', 'Miller', 'wareelizabeth@mcpherson.org');
INSERT INTO ALUMNOS (nombre, apellido, correo) VALUES ('John', 'Powers', 'codynelson@mitchell-brown.biz');
INSERT INTO ALUMNOS (nombre, apellido, correo) VALUES ('Elizabeth', 'Patterson', 'buchananwilliam@gmail.com');
INSERT INTO ALUMNOS (nombre, apellido, correo) VALUES ('Samantha', 'Morris', 'jeffrey47@yahoo.com');
INSERT INTO ALUMNOS (nombre, apellido, correo) VALUES ('Melinda', 'Robinson', 'ramirezjoann@lang-roberts.info');
INSERT INTO ALUMNOS (nombre, apellido, correo) VALUES ('Allen', 'Paul', 'martinmario@montes.info');
INSERT INTO ALUMNOS (nombre, apellido, correo) VALUES ('Tiffany', 'Cervantes', 'wellstyler@yahoo.com');
INSERT INTO ALUMNOS (nombre, apellido, correo) VALUES ('Hunter', 'Pope', 'christywood@moody.com');
INSERT INTO ALUMNOS (nombre, apellido, correo) VALUES ('Robin', 'Mccarthy', 'ssharp@smith.com');
INSERT INTO ALUMNOS (nombre, apellido, correo) VALUES ('Erin', 'Alvarez', 'ntucker@ramos-taylor.com');
INSERT INTO ALUMNOS (nombre, apellido, correo) VALUES ('Melissa', 'Butler', 'qoconnor@reyes.com');
INSERT INTO ALUMNOS (nombre, apellido, correo) VALUES ('Kayla', 'Crawford', 'mcfarlandpaul@jackson-hunter.com');
INSERT INTO ALUMNOS (nombre, apellido, correo) VALUES ('Kenneth', 'Garza', 'raymond42@gray.net');
INSERT INTO ALUMNOS (nombre, apellido, correo) VALUES ('Sarah', 'Chan', 'salasdavid@harris-douglas.net');
INSERT INTO ALUMNOS (nombre, apellido, correo) VALUES ('Kathleen', 'Mcclain', 'michelle71@stephens-martin.net');
INSERT INTO ALUMNOS (nombre, apellido, correo) VALUES ('Kim', 'Walker', 'jerryowens@yahoo.com');
INSERT INTO ALUMNOS (nombre, apellido, correo) VALUES ('Carla', 'Hancock', 'thompsonlisa@adams.net');
INSERT INTO ALUMNOS (nombre, apellido, correo) VALUES ('Jason', 'Garcia', 'aaronlewis@hotmail.com');
INSERT INTO ALUMNOS (nombre, apellido, correo) VALUES ('Nathan', 'Smith', 'paulrodriguez@smith.net');
INSERT INTO ALUMNOS (nombre, apellido, correo) VALUES ('Claire', 'Soto', 'rebecca26@zamora.com');
INSERT INTO ALUMNOS (nombre, apellido, correo) VALUES ('Angela', 'Obrien', 'christophermurphy@yahoo.com');
INSERT INTO ALUMNOS (nombre, apellido, correo) VALUES ('Juan', 'Washington', 'hughesmelissa@yahoo.com');
INSERT INTO ALUMNOS (nombre, apellido, correo) VALUES ('Sheila', 'Moore', 'james55@yahoo.com');
INSERT INTO ALUMNOS (nombre, apellido, correo) VALUES ('Brooke', 'Thomas', 'roberta08@erickson.org');
INSERT INTO ALUMNOS (nombre, apellido, correo) VALUES ('Heather', 'Lopez', 'cedwards@foster-murphy.info');
INSERT INTO ALUMNOS (nombre, apellido, correo) VALUES ('Brian', 'Carter', 'samantha91@gmail.com');
INSERT INTO ALUMNOS (nombre, apellido, correo) VALUES ('Mark', 'Davis', 'elizabeth94@yahoo.com');
INSERT INTO ALUMNOS (nombre, apellido, correo) VALUES ('Harry', 'Woods', 'alvarezmary@hotmail.com');
INSERT INTO ALUMNOS (nombre, apellido, correo) VALUES ('Lance', 'Mckenzie', 'ryanduarte@wilson.org');
INSERT INTO ALUMNOS_CURSOS (ID_ALUMNO, ID_CURSO) VALUES (41, 3);
INSERT INTO ALUMNOS_CURSOS (ID_ALUMNO, ID_CURSO) VALUES (1, 3);
INSERT INTO ALUMNOS_CURSOS (ID_ALUMNO, ID_CURSO) VALUES (4, 3);
INSERT INTO ALUMNOS_CURSOS (ID_ALUMNO, ID_CURSO) VALUES (36, 3);
INSERT INTO ALUMNOS_CURSOS (ID_ALUMNO, ID_CURSO) VALUES (43, 4);
INSERT INTO ALUMNOS_CURSOS (ID_ALUMNO, ID_CURSO) VALUES (26, 2);
INSERT INTO ALUMNOS_CURSOS (ID_ALUMNO, ID_CURSO) VALUES (34, 3);
INSERT INTO ALUMNOS_CURSOS (ID_ALUMNO, ID_CURSO) VALUES (40, 3);
INSERT INTO ALUMNOS_CURSOS (ID_ALUMNO, ID_CURSO) VALUES (16, 1);
INSERT INTO ALUMNOS_CURSOS (ID_ALUMNO, ID_CURSO) VALUES (16, 4);
INSERT INTO ALUMNOS_CURSOS (ID_ALUMNO, ID_CURSO) VALUES (7, 4);
INSERT INTO ALUMNOS_CURSOS (ID_ALUMNO, ID_CURSO) VALUES (14, 3);
INSERT INTO ALUMNOS_CURSOS (ID_ALUMNO, ID_CURSO) VALUES (35, 2);
INSERT INTO ALUMNOS_CURSOS (ID_ALUMNO, ID_CURSO) VALUES (39, 4);
INSERT INTO ALUMNOS_CURSOS (ID_ALUMNO, ID_CURSO) VALUES (31, 5);
INSERT INTO ALUMNOS_CURSOS (ID_ALUMNO, ID_CURSO) VALUES (11, 4);
INSERT INTO ALUMNOS_CURSOS (ID_ALUMNO, ID_CURSO) VALUES (19, 5);
INSERT INTO ALUMNOS_CURSOS (ID_ALUMNO, ID_CURSO) VALUES (14, 1);
INSERT INTO ALUMNOS_CURSOS (ID_ALUMNO, ID_CURSO) VALUES (9, 2);
INSERT INTO ALUMNOS_CURSOS (ID_ALUMNO, ID_CURSO) VALUES (36, 3);
INSERT INTO ALUMNOS_CURSOS (ID_ALUMNO, ID_CURSO) VALUES (20, 5);
INSERT INTO ALUMNOS_CURSOS (ID_ALUMNO, ID_CURSO) VALUES (6, 4);
INSERT INTO ALUMNOS_CURSOS (ID_ALUMNO, ID_CURSO) VALUES (39, 5);
INSERT INTO ALUMNOS_CURSOS (ID_ALUMNO, ID_CURSO) VALUES (41, 2);
INSERT INTO ALUMNOS_CURSOS (ID_ALUMNO, ID_CURSO) VALUES (15, 2);
INSERT INTO ALUMNOS_CURSOS (ID_ALUMNO, ID_CURSO) VALUES (8, 1);
INSERT INTO ALUMNOS_CURSOS (ID_ALUMNO, ID_CURSO) VALUES (7, 1);
INSERT INTO ALUMNOS_CURSOS (ID_ALUMNO, ID_CURSO) VALUES (18, 5);
INSERT INTO ALUMNOS_CURSOS (ID_ALUMNO, ID_CURSO) VALUES (10, 3);
INSERT INTO ALUMNOS_CURSOS (ID_ALUMNO, ID_CURSO) VALUES (18, 4);
INSERT INTO ALUMNOS_CURSOS (ID_ALUMNO, ID_CURSO) VALUES (11, 4);
INSERT INTO ALUMNOS_CURSOS (ID_ALUMNO, ID_CURSO) VALUES (33, 4);
INSERT INTO ALUMNOS_CURSOS (ID_ALUMNO, ID_CURSO) VALUES (6, 5);
INSERT INTO ALUMNOS_CURSOS (ID_ALUMNO, ID_CURSO) VALUES (31, 4);
INSERT INTO ALUMNOS_CURSOS (ID_ALUMNO, ID_CURSO) VALUES (41, 3);
INSERT INTO ALUMNOS_CURSOS (ID_ALUMNO, ID_CURSO) VALUES (22, 3);
INSERT INTO ALUMNOS_CURSOS (ID_ALUMNO, ID_CURSO) VALUES (4, 5);
INSERT INTO ALUMNOS_CURSOS (ID_ALUMNO, ID_CURSO) VALUES (35, 2);
INSERT INTO ALUMNOS_CURSOS (ID_ALUMNO, ID_CURSO) VALUES (4, 1);
INSERT INTO ALUMNOS_CURSOS (ID_ALUMNO, ID_CURSO) VALUES (50, 3);
INSERT INTO ALUMNOS_CURSOS (ID_ALUMNO, ID_CURSO) VALUES (19, 4);
INSERT INTO ALUMNOS_CURSOS (ID_ALUMNO, ID_CURSO) VALUES (35, 2);
INSERT INTO ALUMNOS_CURSOS (ID_ALUMNO, ID_CURSO) VALUES (11, 5);
INSERT INTO ALUMNOS_CURSOS (ID_ALUMNO, ID_CURSO) VALUES (42, 5);
INSERT INTO ALUMNOS_CURSOS (ID_ALUMNO, ID_CURSO) VALUES (7, 4);
INSERT INTO ALUMNOS_CURSOS (ID_ALUMNO, ID_CURSO) VALUES (12, 1);
INSERT INTO ALUMNOS_CURSOS (ID_ALUMNO, ID_CURSO) VALUES (26, 1);
INSERT INTO ALUMNOS_CURSOS (ID_ALUMNO, ID_CURSO) VALUES (40, 5);
INSERT INTO ALUMNOS_CURSOS (ID_ALUMNO, ID_CURSO) VALUES (38, 4);
INSERT INTO ALUMNOS_CURSOS (ID_ALUMNO, ID_CURSO) VALUES (15, 4);
INSERT INTO ALUMNOS_CURSOS (ID_ALUMNO, ID_CURSO) VALUES (19, 3);
INSERT INTO ALUMNOS_CURSOS (ID_ALUMNO, ID_CURSO) VALUES (24, 2);
INSERT INTO ALUMNOS_CURSOS (ID_ALUMNO, ID_CURSO) VALUES (5, 1);
INSERT INTO ALUMNOS_CURSOS (ID_ALUMNO, ID_CURSO) VALUES (24, 1);
INSERT INTO ALUMNOS_CURSOS (ID_ALUMNO, ID_CURSO) VALUES (2, 3);
INSERT INTO ALUMNOS_CURSOS (ID_ALUMNO, ID_CURSO) VALUES (22, 1);
INSERT INTO ALUMNOS_CURSOS (ID_ALUMNO, ID_CURSO) VALUES (19, 4);
INSERT INTO ALUMNOS_CURSOS (ID_ALUMNO, ID_CURSO) VALUES (6, 2);
INSERT INTO ALUMNOS_CURSOS (ID_ALUMNO, ID_CURSO) VALUES (29, 2);
INSERT INTO ALUMNOS_CURSOS (ID_ALUMNO, ID_CURSO) VALUES (26, 4);
INSERT INTO ALUMNOS_CURSOS (ID_ALUMNO, ID_CURSO) VALUES (47, 3);
INSERT INTO ALUMNOS_CURSOS (ID_ALUMNO, ID_CURSO) VALUES (19, 5);
INSERT INTO ALUMNOS_CURSOS (ID_ALUMNO, ID_CURSO) VALUES (36, 5);
INSERT INTO ALUMNOS_CURSOS (ID_ALUMNO, ID_CURSO) VALUES (25, 2);
INSERT INTO ALUMNOS_CURSOS (ID_ALUMNO, ID_CURSO) VALUES (49, 3);
INSERT INTO ALUMNOS_CURSOS (ID_ALUMNO, ID_CURSO) VALUES (50, 1);
INSERT INTO ALUMNOS_CURSOS (ID_ALUMNO, ID_CURSO) VALUES (34, 4);
INSERT INTO ALUMNOS_CURSOS (ID_ALUMNO, ID_CURSO) VALUES (24, 3);
INSERT INTO ALUMNOS_CURSOS (ID_ALUMNO, ID_CURSO) VALUES (41, 1);
INSERT INTO ALUMNOS_CURSOS (ID_ALUMNO, ID_CURSO) VALUES (21, 2);
INSERT INTO ALUMNOS_CURSOS (ID_ALUMNO, ID_CURSO) VALUES (17, 5);
INSERT INTO ALUMNOS_CURSOS (ID_ALUMNO, ID_CURSO) VALUES (21, 2);
INSERT INTO ALUMNOS_CURSOS (ID_ALUMNO, ID_CURSO) VALUES (39, 1);
INSERT INTO ALUMNOS_CURSOS (ID_ALUMNO, ID_CURSO) VALUES (4, 5);
INSERT INTO ALUMNOS_CURSOS (ID_ALUMNO, ID_CURSO) VALUES (24, 5);
