# Generated by Django 3.2.7 on 2021-10-02 02:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0001_migracion_inicial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='comprobantemodel',
            table='comprobantes',
        ),
    ]
